#!/bin/bash

check_no_diffmarkers_or_whitespace_errors() {
  # If there are whitespace errors, print the offending file names and fail.
  set -e
  git diff-index --check --cached "${1}" --
  set +e
}

check_no_do_not_submit() {
  local tag="DO""NOT""SUBMIT"
  local filenames="$1"

  if [[ -z "${filenames}" ]]; then
    return
  fi

  set +e
  output="$(echo "${filenames}" | xargs grep -H -ni "${tag}" -- 2>/dev/null)"
  found=$?
  set -e

  if [[ $found -eq 0 ]]; then
    echo "${output}"
    echo "${tag} tag found, aborting"
    exit 1
  fi
}

if git rev-parse --verify HEAD >/dev/null 2>&1; then
  against=HEAD
else
  # Initial commit: diff against an empty tree object
  against=$(git hash-object -t tree /dev/null)
fi

# Redirect output to stderr.
exec 1>&2

readonly added_and_modified_filenames="$(git diff --cached --name-only --diff-filter=d)"
readonly changed_kt_filenames="$(echo "${added_and_modified_filenames}" | grep -E '.*\.(kt)$')"

function run_ktfmt() {
  if [[ -z "${changed_kt_filenames}" ]]; then
    return
  fi
  files_to_format="$(echo "${changed_kt_filenames}" | grep -v '3rdparty' || true)"
  if [[ -n "${files_to_format}" ]]; then
    if ! ./gradlew ktfmtPrecommit; then
      echo "ktfmtPrecommit failed, aborting commit"
      exit 1
    fi
    echo "${files_to_format}" | xargs git add
  fi
}

run_ktfmt
check_no_do_not_submit "${added_and_modified_filenames}"
check_no_diffmarkers_or_whitespace_errors "${against}"
